import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./background.css";
import FooterPlaylist from "@/src/features/playlist/ui/FooterPlaylist";
import Navbar from "@/src/components/ui/Navbar";
import { Footer } from "@/src/components/ui/Footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        //className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className={`antialiased`}

      >
        <Navbar/>
        {children}
          <FooterPlaylist />
        <Footer/>
      </body>
    </html>
  );
}
